### ISSUE TITLE
Error while saving file

### ISSUE THREAD

**Issue by festadurador** [tenacityteam/tenacity#112]
[This comment was an extremely offensive word and has been removed by a moderator.]

**Comment by EricBright** [comment]
@emabrey this issue must be deleted as blunt, racist, slur and the author should be banned in my opinion.

**Comment by NormanOsborn** [comment]
> @emabrey this issue must be deleted as blunt, racist, slur and the author should be banned in my opinion.

He's obviously just quoting the error message, he didn't say it directly. The previous maintainer of the fork quoted several slurs, and yet I see no complaints about it.

**Comment by dascar5** [comment]
> @emabrey @panos this issue must be deleted as blunt, racist, slur and the author should be banned in my opinion.

Okay buddy, I see you've been harassing users for the last hour. Not only did I report you, but I will also be contacting local authorities. Maybe they can teach you a thing or two about harassment online.

**Comment by notevenaperson** [comment]
> > @emabrey this issue must be deleted as blunt, racist, slur and the author should be banned in my opinion.
> 
> He's obviously just quoting the error message, he didn't say it directly. The previous maintainer of the fork quoted several slurs, and yet I see no complaints about it.

I'm concerned some use quoting to not be accountable for their hate speech.

**Comment by dascar5** [comment]
> > > @emabrey this issue must be deleted as blunt, racist, slur and the author should be banned in my opinion.
> > 
> > 
> > He's obviously just quoting the error message, he didn't say it directly. The previous maintainer of the fork quoted several slurs, and yet I see no complaints about it.
> 
> I'm concerned some use quoting to not be accountable for their hate speech.

I am concerned about your concerning implications.

**Comment by emabrey** [comment]
> 
> 
> > > @emabrey this issue must be deleted as blunt, racist, slur and the author should be banned in my opinion.
> > 
> > 
> > He's obviously just quoting the error message, he didn't say it directly. The previous maintainer of the fork quoted several slurs, and yet I see no complaints about it.
> 
> I'm concerned quoting can be used to remove accountability for hate speech.

Context matters.

**Comment by binex-dsk** [comment]
> > > @emabrey this issue must be deleted as blunt, racist, slur and the author should be banned in my opinion.
> > 
> > 
> > He's obviously just quoting the error message, he didn't say it directly. The previous maintainer of the fork quoted several slurs, and yet I see no complaints about it.
> 
> I'm concerned quoting can be used to remove accountability for hate speech.

by that logic cookie is accountable for the various slurs which he quoted.

i believe this project should be held accountable for producing an error message containing an extremely racist slur
