### ISSUE TITLE
Does the head developer Cookie Engineer still work for the US Military?

### ISSUE THREAD

**Issue by Kill-Animals** [tenacityteam/tenacity#98]
I think we deserve an answer. He frantically had these posts deleted when people started pointing out this conflict of interest.

**Comment by alicemargatroid** [comment]
Conflict of interest? How is working for the US military necessarily a conflict of interest, given the context is MUSE adding stuff that the community did not want to the repo?

**Comment by EricBright** [comment]
@emabrey can be closed as invalid. Has nothing to do with the code or the community.

**Comment by cookiengineer** [comment]
No he does not. I work for EDAG ffs. Go on goddamn LinkedIn, man.
